spring.application.name=mechcalc
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api/v1

spring.datasource.url=${SPRING_DATASOURCE_URL:${SPRING_DATA_SOURCE_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${SPRING_DATA_SOURCE_USERNAME}}

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.hikari.data-source-properties.prepareThreshold=0

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always

# Logging Configuration
logging.level.root=INFO
logging.level.com.socodo.mechcalc=${APP_LOG_LEVEL:INFO}
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=${HIBERNATE_SQL_LOG_LEVEL:WARN}
logging.level.org.hibernate.orm.jdbc.bind=${HIBERNATE_BIND_LOG_LEVEL:WARN}
logging.level.org.hibernate.orm.connections.pooling=WARN

# OpenAPI/Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:3600000}
security.jwt.refresh-token-expiration=${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:604800000}

# Servlet Encoding
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
server.servlet.encoding.force-request=true
server.servlet.encoding.force-response=true

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

# Reverse Proxy/Tunnel
server.forward-headers-strategy=framework
