spring.application.name=mechcalc
spring.config.import=optional:file:.env[.properties]

# Server Configuration (Sửa lại context-path cho hợp lý)
server.port=${SERVER_PORT:8080}
server.servlet.context-path=/api/v1

spring.datasource.url=${SPRING_DATA_SOURCE_URL:jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?user=postgres.mfmubhjivbgelpheroyu&password=Ho@i23523456789)&sslmode=require}
spring.datasource.username=postgres.mfmubhjivbgelpheroyu

spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Logging Configuration
logging.level.root=INFO
logging.level.com.socodo.mechcalc=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# OpenAPI/Swagger Configuration
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration
security.jwt.secret-key=${SECURITY_JWT_SECRET_KEY:ZmFsbGJhY2stc2VjcmV0LWtleS1wbGVhc2UtY2hhbmdlLWluLXByb2R1Y3Rpb24=}
security.jwt.expiration-time=${SECURITY_JWT_EXPIRATION_TIME:3600000}
security.jwt.refresh-token-expiration=${SECURITY_JWT_REFRESH_TOKEN_EXPIRATION:604800000}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}