INSERT INTO gear_catalogs (
    id,
    catalog_code,
    gear_detail,
    material,
    heat_treatment,
    size_limit_mm,
    hardness_hb,
    sigma_b,
    sigma_ch,
    contact_fatigue_limit_coefficient,
    contact_fatigue_limit_constant,
    contact_safety_factor,
    bending_fatigue_limit_coefficient,
    bending_safety_factor
) VALUES
(
    1,
    'GEAR_DRIVING_40XH_HB300',
    'Banh dan',
    '40XH',
    'Toi cai thien',
    100,
    300,
    850,
    600,
    2,
    70,
    1.1,
    1.8,
    1.75
),
(
    2,
    'GEAR_DRIVEN_40XH_HB290',
    'Banh bi dan',
    '40XH',
    'Toi cai thien',
    100,
    290,
    850,
    600,
    2,
    70,
    1.1,
    1.8,
    1.75
) ON CONFLICT (catalog_code) DO UPDATE SET
    gear_detail = EXCLUDED.gear_detail,
    material = EXCLUDED.material,
    heat_treatment = EXCLUDED.heat_treatment,
    size_limit_mm = EXCLUDED.size_limit_mm,
    hardness_hb = EXCLUDED.hardness_hb,
    sigma_b = EXCLUDED.sigma_b,
    sigma_ch = EXCLUDED.sigma_ch,
    contact_fatigue_limit_coefficient = EXCLUDED.contact_fatigue_limit_coefficient,
    contact_fatigue_limit_constant = EXCLUDED.contact_fatigue_limit_constant,
    contact_safety_factor = EXCLUDED.contact_safety_factor,
    bending_fatigue_limit_coefficient = EXCLUDED.bending_fatigue_limit_coefficient,
    bending_safety_factor = EXCLUDED.bending_safety_factor;
